import type { ImageSourcePropType } from "react-native";

/**
 * Canvas sticker tool catalog (mobile copy of the shared
 * `@one-colored-pixel/coloring-ui` CANVAS_STICKERS) + the bundled-PNG
 * registry. The 36 transparent stickers a kid stamps onto the canvas — flat
 * vector art generated by `apps/chunky-crayon-web/scripts/
 * generate-canvas-stickers.ts`, copied into `assets/stickers/canvas/`.
 *
 * Mobile keeps a LOCAL copy (ids must stay byte-identical to the package's
 * catalog) rather than importing the web-oriented coloring-ui package into the
 * RN bundle — the same duplicate-catalog pattern as lib/colo/catalog.ts and
 * lib/avatars.ts. `STICKER_IMAGES` resolves a sticker id → bundled PNG via a
 * static require() map (Metro needs static paths). Every sticker is an
 * illustrated PNG; there is no emoji fallback.
 */

export type CanvasStickerCategory =
  | "stars"
  | "hearts"
  | "shapes"
  | "nature"
  | "animals"
  | "fun";

export type CanvasSticker = {
  id: string;
  name: string;
  category: CanvasStickerCategory;
};

export const CANVAS_STICKERS: CanvasSticker[] = [
  // stars
  { id: "star-classic", name: "Star", category: "stars" },
  { id: "star-shooting", name: "Shooting Star", category: "stars" },
  { id: "sparkles", name: "Sparkles", category: "stars" },
  { id: "star-burst", name: "Star Burst", category: "stars" },
  { id: "moon-crescent", name: "Crescent Moon", category: "stars" },
  { id: "comet", name: "Comet", category: "stars" },
  // hearts
  { id: "heart-red", name: "Red Heart", category: "hearts" },
  { id: "heart-double", name: "Two Hearts", category: "hearts" },
  { id: "heart-sparkle", name: "Sparkle Heart", category: "hearts" },
  { id: "heart-arrow", name: "Heart with Arrow", category: "hearts" },
  { id: "heart-rainbow", name: "Rainbow Heart", category: "hearts" },
  { id: "heart-wings", name: "Winged Heart", category: "hearts" },
  // shapes
  { id: "circle", name: "Circle", category: "shapes" },
  { id: "square", name: "Square", category: "shapes" },
  { id: "triangle", name: "Triangle", category: "shapes" },
  { id: "diamond", name: "Diamond", category: "shapes" },
  { id: "hexagon", name: "Hexagon", category: "shapes" },
  { id: "star-outline", name: "Star Shape", category: "shapes" },
  // nature
  { id: "flower-daisy", name: "Daisy", category: "nature" },
  { id: "sun-smiley", name: "Sunshine", category: "nature" },
  { id: "rainbow", name: "Rainbow", category: "nature" },
  { id: "cloud", name: "Cloud", category: "nature" },
  { id: "butterfly", name: "Butterfly", category: "nature" },
  { id: "leaf", name: "Leaf", category: "nature" },
  // animals
  { id: "cat", name: "Cat", category: "animals" },
  { id: "dog", name: "Dog", category: "animals" },
  { id: "bunny", name: "Bunny", category: "animals" },
  { id: "bear", name: "Bear", category: "animals" },
  { id: "fox", name: "Fox", category: "animals" },
  { id: "fish", name: "Fish", category: "animals" },
  // fun
  { id: "crown", name: "Crown", category: "fun" },
  { id: "rocket", name: "Rocket", category: "fun" },
  { id: "balloon", name: "Balloon", category: "fun" },
  { id: "gift", name: "Gift", category: "fun" },
  { id: "cupcake", name: "Cupcake", category: "fun" },
  { id: "party-popper", name: "Party Popper", category: "fun" },
];

export const CANVAS_STICKER_CATEGORIES: {
  category: CanvasStickerCategory;
  name: string;
}[] = [
  { category: "stars", name: "Stars" },
  { category: "hearts", name: "Hearts" },
  { category: "shapes", name: "Shapes" },
  { category: "nature", name: "Nature" },
  { category: "animals", name: "Animals" },
  { category: "fun", name: "Fun" },
];

export const getCanvasSticker = (id: string): CanvasSticker | undefined =>
  CANVAS_STICKERS.find((s) => s.id === id);

export const getCanvasStickersByCategory = (
  category: CanvasStickerCategory,
): CanvasSticker[] => CANVAS_STICKERS.filter((s) => s.category === category);

/** Bundled transparent PNG per sticker id (static require() — Metro requirement). */
export const CANVAS_STICKER_IMAGES: Record<string, ImageSourcePropType> = {
  "star-classic": require("@/assets/stickers/canvas/star-classic.png"),
  "star-shooting": require("@/assets/stickers/canvas/star-shooting.png"),
  sparkles: require("@/assets/stickers/canvas/sparkles.png"),
  "star-burst": require("@/assets/stickers/canvas/star-burst.png"),
  "moon-crescent": require("@/assets/stickers/canvas/moon-crescent.png"),
  comet: require("@/assets/stickers/canvas/comet.png"),
  "heart-red": require("@/assets/stickers/canvas/heart-red.png"),
  "heart-double": require("@/assets/stickers/canvas/heart-double.png"),
  "heart-sparkle": require("@/assets/stickers/canvas/heart-sparkle.png"),
  "heart-arrow": require("@/assets/stickers/canvas/heart-arrow.png"),
  "heart-rainbow": require("@/assets/stickers/canvas/heart-rainbow.png"),
  "heart-wings": require("@/assets/stickers/canvas/heart-wings.png"),
  circle: require("@/assets/stickers/canvas/circle.png"),
  square: require("@/assets/stickers/canvas/square.png"),
  triangle: require("@/assets/stickers/canvas/triangle.png"),
  diamond: require("@/assets/stickers/canvas/diamond.png"),
  hexagon: require("@/assets/stickers/canvas/hexagon.png"),
  "star-outline": require("@/assets/stickers/canvas/star-outline.png"),
  "flower-daisy": require("@/assets/stickers/canvas/flower-daisy.png"),
  "sun-smiley": require("@/assets/stickers/canvas/sun-smiley.png"),
  rainbow: require("@/assets/stickers/canvas/rainbow.png"),
  cloud: require("@/assets/stickers/canvas/cloud.png"),
  butterfly: require("@/assets/stickers/canvas/butterfly.png"),
  leaf: require("@/assets/stickers/canvas/leaf.png"),
  cat: require("@/assets/stickers/canvas/cat.png"),
  dog: require("@/assets/stickers/canvas/dog.png"),
  bunny: require("@/assets/stickers/canvas/bunny.png"),
  bear: require("@/assets/stickers/canvas/bear.png"),
  fox: require("@/assets/stickers/canvas/fox.png"),
  fish: require("@/assets/stickers/canvas/fish.png"),
  crown: require("@/assets/stickers/canvas/crown.png"),
  rocket: require("@/assets/stickers/canvas/rocket.png"),
  balloon: require("@/assets/stickers/canvas/balloon.png"),
  gift: require("@/assets/stickers/canvas/gift.png"),
  cupcake: require("@/assets/stickers/canvas/cupcake.png"),
  "party-popper": require("@/assets/stickers/canvas/party-popper.png"),
};
