/**
 * Portrait prompts for character generation.
 *
 * Every character gets TWO assets, generated by the worker in two
 * sequential gpt-image-2 calls:
 *
 *   1. Line-art portrait  — `buildCharacterLineArtPrompt`.
 *      A clean coloring-book outline. This is the canonical asset: it's
 *      what the coloring-page pipeline conditions on when the character
 *      appears in a scene (line-art conditioning yields cleaner pages
 *      than colored conditioning).
 *
 *   2. Colored illustration — `buildCharacterColoringPrompt`.
 *      The line-art from step 1 is fed back into `images.edit` as the
 *      reference image, and this prompt says "color it in" in the warm
 *      Chunky Crayon brand recipe (the same recipe as the scene /
 *      character-builder tile illustrations). Because it's drawn ON the
 *      line-art, the two assets are guaranteed to match — same pose,
 *      same proportions, same details. This is the version shown in the
 *      UI (the /characters grid, the cockpit).
 *
 * Why two prompts instead of one: a single prompt that asked for both
 * "line-art" and "colored" contradicted itself and the model resolved
 * toward line-art, so the colored asset never really existed. Splitting
 * into two single-purpose prompts removes the contradiction.
 *
 * Both build on `ExtractedCharacter.referenceSheetPrompt`, which already
 * inlines every signatureDetail verbatim and ends with the "single
 * character / plain white background / no scenery" anchor.
 */

import type { ExtractedCharacter } from './trait-extraction';

/**
 * Prompt for call 1 — the clean line-art portrait.
 *
 * Pure outline, no fills. Closed contours so the shape reads as a
 * proper coloring-book character and conditions cleanly when this
 * character is dropped into a coloring page.
 */
export const buildCharacterLineArtPrompt = ({
  name,
  extracted,
}: {
  name: string;
  extracted: ExtractedCharacter;
}): string => {
  return `Character: ${name}.

${extracted.referenceSheetPrompt}

Style: black-and-white line-art for a children's coloring book. Bold
uniform-weight black outlines like a Sharpie marker. NO colour, NO
shading, NO grey fills — pure white interior, outline only. Single
character only, no other figures, no props beyond what the signature
details name. Plain pure-white background.

Composition: centred, full-body, facing slightly toward the camera, a
neutral pose (standing or sitting), arms visible. No motion blur, no
action poses. A small margin of white space on all sides.

Outlines must be CLOSED CONTOURS — every shape fully sealed, no breaks
or gaps. This line-art is the reference the character is drawn from in
future coloring pages, so the contours must be watertight.

My prompt has full detail; do not add anything not listed.`;
};

/**
 * Prompt for call 2 — color in the line-art (passed as the `image`
 * reference to `images.edit`).
 *
 * The Chunky Crayon brand recipe, identical in spirit to
 * `scripts/generate-scene-thumbnails.ts`: warm dark-brown outlines,
 * flat bright fills, pink cheek blush, no gradients. The picked body
 * colour is named verbatim from `signatureDetails` (which always
 * contains a "<colour> body colour" entry).
 */
export const buildCharacterColoringPrompt = ({
  name,
  extracted,
}: {
  name: string;
  extracted: ExtractedCharacter;
}): string => {
  // The colour the kid picked is already in signatureDetails as e.g.
  // "orange body colour". Inline the whole list so the colour and every
  // feature are stated; the model is colouring an existing line-art so
  // it mainly needs the palette + style, not the structure.
  const details = extracted.signatureDetails.join('; ');

  return `Colour in this line-art drawing of ${name}, a ${extracted.species}.

Keep the exact outline, pose and proportions of the provided line-art —
do not redraw the character, only add colour inside the existing
shapes.

Style: the friendly Chunky Crayon look. Thick warm dark-brown outlines
(around #5a3a1f), not pure black. Bright flat colour fills, no
gradients, no painterly shading. If the character has a face, add small
soft pink circular cheek blushes. Keep colours child-friendly and
saturated but not neon.

Apply these specific details exactly: ${details}.

Single character, plain pure-white background, no scenery, no text.`;
};
