"use client";

import { useState, useCallback, useRef } from "react";

export type ReferenceColorState = {
  /** Whether the reference image is being generated by AI */
  isGenerating: boolean;
  /** Whether the reference is loaded and ready to sample colors from */
  isReady: boolean;
  /** Error message if generation or loading failed */
  error: string | null;
  /** The reference image as a base64 data URL (for preview) */
  referenceImageUrl: string | null;
};

export type UseReferenceColorReturn = {
  state: ReferenceColorState;
  /**
   * Load a reference image (base64 data URL or regular URL).
   * Draws it onto an internal canvas for pixel sampling.
   */
  loadReference: (imageUrl: string) => Promise<boolean>;
  /**
   * Get the color at a specific pixel position from the reference.
   * Coordinates should be in the reference image's pixel space.
   * @returns Hex color string (e.g., "#FF5733") or null if no reference loaded
   */
  getColorAt: (x: number, y: number) => string | null;
  /**
   * Get the color at normalized coordinates (0-1 range).
   * Useful when the source canvas has different dimensions than the reference.
   */
  getColorAtNormalized: (normX: number, normY: number) => string | null;
  /**
   * Get colors at multiple points, scaled from source dimensions to reference dimensions.
   * Used by Auto Color to sample colors at region centroids.
   */
  getColorsAtPoints: (
    points: Array<{ x: number; y: number }>,
    sourceWidth: number,
    sourceHeight: number,
  ) => Array<{ x: number; y: number; color: string }>;
  /** Get the reference canvas dimensions */
  getDimensions: () => { width: number; height: number } | null;
  /** Clear the reference */
  reset: () => void;
};

/**
 * Hook for reference-image-based coloring.
 *
 * Loads an AI-generated colored reference image into an offscreen canvas
 * and provides pixel-accurate color sampling. Used by both Auto Color
 * (sample at region centroids) and Magic Brush (sample at brush position).
 */
export function useReferenceColor(): UseReferenceColorReturn {
  const [state, setState] = useState<ReferenceColorState>({
    isGenerating: false,
    isReady: false,
    error: null,
    referenceImageUrl: null,
  });

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const imageDataRef = useRef<ImageData | null>(null);

  const loadReference = useCallback(
    async (imageUrl: string): Promise<boolean> => {
      setState((s) => ({
        ...s,
        isGenerating: false,
        isReady: false,
        error: null,
        referenceImageUrl: imageUrl,
      }));

      return new Promise<boolean>((resolve) => {
        const img = new Image();
        img.crossOrigin = "anonymous";

        img.onload = () => {
          // Draw onto offscreen canvas for pixel sampling
          const canvas = document.createElement("canvas");
          canvas.width = img.naturalWidth;
          canvas.height = img.naturalHeight;
          const ctx = canvas.getContext("2d");

          if (!ctx) {
            setState((s) => ({
              ...s,
              error: "Failed to create canvas context",
            }));
            resolve(false);
            return;
          }

          ctx.drawImage(img, 0, 0);
          canvasRef.current = canvas;

          // Cache full ImageData for fast pixel lookups
          imageDataRef.current = ctx.getImageData(
            0,
            0,
            canvas.width,
            canvas.height,
          );

          setState((s) => ({
            ...s,
            isReady: true,
            error: null,
          }));

          console.log(
            `[ReferenceColor] Loaded reference: ${canvas.width}x${canvas.height}`,
          );
          resolve(true);
        };

        img.onerror = () => {
          setState((s) => ({
            ...s,
            error: "Failed to load reference image",
          }));
          resolve(false);
        };

        img.src = imageUrl;
      });
    },
    [],
  );

  const getColorAt = useCallback((x: number, y: number): string | null => {
    const data = imageDataRef.current;
    if (!data) return null;

    const px = Math.floor(x);
    const py = Math.floor(y);

    if (px < 0 || px >= data.width || py < 0 || py >= data.height) return null;

    const idx = (py * data.width + px) * 4;
    const r = data.data[idx];
    const g = data.data[idx + 1];
    const b = data.data[idx + 2];

    return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`.toUpperCase();
  }, []);

  const getColorAtNormalized = useCallback(
    (normX: number, normY: number): string | null => {
      const data = imageDataRef.current;
      if (!data) return null;

      const x = normX * data.width;
      const y = normY * data.height;
      return getColorAt(x, y);
    },
    [getColorAt],
  );

  const getColorsAtPoints = useCallback(
    (
      points: Array<{ x: number; y: number }>,
      sourceWidth: number,
      sourceHeight: number,
    ): Array<{ x: number; y: number; color: string }> => {
      const data = imageDataRef.current;
      if (!data) return [];

      const scaleX = data.width / sourceWidth;
      const scaleY = data.height / sourceHeight;

      const results: Array<{ x: number; y: number; color: string }> = [];

      for (const point of points) {
        const refX = Math.floor(point.x * scaleX);
        const refY = Math.floor(point.y * scaleY);
        const color = getColorAt(refX, refY);

        if (color) {
          results.push({ x: point.x, y: point.y, color });
        }
      }

      return results;
    },
    [getColorAt],
  );

  const getDimensions = useCallback((): {
    width: number;
    height: number;
  } | null => {
    const canvas = canvasRef.current;
    if (!canvas) return null;
    return { width: canvas.width, height: canvas.height };
  }, []);

  const reset = useCallback(() => {
    canvasRef.current = null;
    imageDataRef.current = null;
    setState({
      isGenerating: false,
      isReady: false,
      error: null,
      referenceImageUrl: null,
    });
  }, []);

  return {
    state,
    loadReference,
    getColorAt,
    getColorAtNormalized,
    getColorsAtPoints,
    getDimensions,
    reset,
  };
}
