/**
 * B-roll judge. Takes a generated clip's extracted frames and asks
 * Claude Opus 4.7 to evaluate it against a 6-criterion rubric. Opus is
 * meaningfully better than Sonnet at cross-frame comparison tasks like
 * "has the dragon's spike pattern drifted?" — which is most of what this
 * rubric checks for.
 *
 * The rubric system prompt is cached via Anthropic's prompt caching
 * (`cacheControl: { type: 'ephemeral' }`), so the per-clip cost after
 * the first call drops to just the frame upload + ~200-token response.
 * Expected cost per clip: ~$0.01 cached, ~$0.015 uncached.
 *
 * Called automatically at the end of generate-broll.ts; also importable
 * from scripts/review-broll.ts to re-judge existing clips.
 */

import { generateObject } from 'ai';
import { anthropic } from '@ai-sdk/anthropic';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { z } from 'zod';
import type { BrollJudgement } from './schema';

// Pinned explicitly to Opus 4.7. Don't swap this without re-evaluating
// judgement quality on the same set of clips — see memory for model
// selection notes.
const OPUS_MODEL_ID = 'claude-opus-4-7';

const CRITERION_SCHEMA = z.object({
  pass: z.boolean(),
  evidence: z
    .string()
    .describe(
      'One-sentence specific evidence citing frame numbers where possible.',
    ),
});

const JUDGEMENT_SCHEMA = z.object({
  verdict: z
    .enum(['SHIP', 'ITERATE', 'REGENERATE'])
    .describe(
      'SHIP: ready to use as-is. ITERATE: usable but improvable. REGENERATE: broken, retry.',
    ),
  topIssue: z
    .string()
    .nullable()
    .describe(
      'One line on the single biggest problem (null if verdict is SHIP).',
    ),
  criteria: z.object({
    artworkStability: CRITERION_SCHEMA.describe(
      'Does the coloring page illustration stay consistent across ALL frames? No morph, no ghost, no doubling, no details changing.',
    ),
    compositionStability: CRITERION_SCHEMA.describe(
      'Does the camera stay locked and do surrounding objects (crayons, water ring, crumbs) stay in the same positions?',
    ),
    handAnatomy: CRITERION_SCHEMA.describe(
      'Do visible hands/arms have correct finger count, natural shape, and consistent fingers across every frame?',
    ),
    colourPersistence: CRITERION_SCHEMA.describe(
      'Does any new colour added to the page stay visible? Or does it flicker / appear and disappear? (If no new colour is added at all, this is a PASS — nothing to flicker.)',
    ),
    motionPlausibility: CRITERION_SCHEMA.describe(
      'Does the motion read as a real human action (natural rhythm, natural arm curvature) rather than AI-stuttery or unnaturally smooth?',
    ),
    aiGleam: CRITERION_SCHEMA.describe(
      'Is the rendering FREE of AI-obvious tells — waxy skin, unnaturally clean surfaces, glossy symmetry, perfectly-placed objects? A PASS means it looks like a real iPhone photo.',
    ),
  }),
});

const RUBRIC_SYSTEM_PROMPT = `You are a senior video ad quality judge for Chunky Crayon (a kids' coloring page app). You evaluate AI-generated b-roll clips for use in Meta feed / Stories / TikTok ads targeting parents.

Your job: examine 5-10 frames extracted from a short (5s) AI-generated video and judge it on 6 specific criteria. Be harsh but specific. The goal is to catch problems BEFORE a human wastes time watching the whole clip.

Context on the b-roll being judged: these clips show a child's hand colouring a printed coloring page with a wax crayon. The still is generated by Nano Banana Pro; the motion is generated by Kling v3 Pro or Seedance 2. Common failure modes you should watch for:

1. ARTWORK STABILITY — the printed coloring page content (dinosaurs, dragons, etc.) sometimes morphs or shifts between frames. Spike patterns change, helmets swap sides, planets move. If you see any drift, FAIL.
2. COMPOSITION STABILITY — the camera should be completely locked. Watch for page position shifting, table surface drifting, crayons repositioning. Even subtle drift = FAIL.
3. HAND ANATOMY — AI sometimes renders 6 fingers, or fingers merge, or wrist angles become impossible between frames. Look closely at every frame with a visible hand.
4. COLOUR PERSISTENCE — if the clip shows new crayon colour being added, that colour should STAY visible once applied. Flickering (appears in frame 3, gone in frame 4) is a common Seedance failure mode and is FAIL-worthy.
5. MOTION PLAUSIBILITY — arm/hand motion should look like a real 5-year-old, not too-smooth interpolation or jitter.
6. AI GLEAM — a PASS means it looks like an amateur iPhone photo. FAIL if skin is waxy, surfaces are unnaturally clean, lighting looks studio-perfect, or scattered objects are too symmetrically placed.

For each criterion, give a single sentence citing specific frame numbers as evidence. Then set the overall verdict:

- SHIP: all criteria pass. Ready to use in an ad.
- ITERATE: 1-2 minor criteria fail but the clip is usable. Could improve with prompt tweaks.
- REGENERATE: 2+ criteria fail, or any single criterion fails badly. Retry with new seed or revised prompt.

Set topIssue to a single sentence describing the biggest problem (null if SHIP).`;

/**
 * Judge a b-roll clip using its extracted frames.
 *
 * @param framesDir — local path to the frames directory (per-second .jpg
 *   files named f-01.jpg … f-05.jpg)
 * @returns BrollJudgement suitable for storing in broll-assets.json
 */
export async function judgeBrollClip(
  framesDir: string,
): Promise<BrollJudgement> {
  // Load every f-XX.jpg frame in order. Half-second frames (h-*.jpg) are
  // skipped — we give Opus 5 whole-second samples which is enough for
  // cross-frame comparison without blowing the token budget.
  const frameBuffers: Buffer[] = [];
  for (let i = 1; i <= 10; i += 1) {
    try {
      const padded = String(i).padStart(2, '0');
      const buffer = await readFile(resolve(framesDir, `f-${padded}.jpg`));
      frameBuffers.push(buffer);
    } catch {
      break; // No more frames
    }
  }
  if (frameBuffers.length === 0) {
    throw new Error(`No frames found in ${framesDir}`);
  }

  const userContent: Array<
    | { type: 'text'; text: string }
    | { type: 'image'; image: Uint8Array; mediaType: string }
  > = [
    {
      type: 'text',
      text: `Here are ${frameBuffers.length} frames (one per second) extracted from a 5-second AI-generated b-roll clip. Evaluate it against all 6 criteria.`,
    },
    ...frameBuffers.map((buffer, i) => ({
      type: 'image' as const,
      image: new Uint8Array(buffer),
      mediaType: 'image/jpeg' as const,
      // Prompt-cache the frames too — but frames are per-clip, so caching
      // them has no benefit. Only the system prompt is worth caching.
    })),
    {
      type: 'text',
      text: 'Return your judgement as structured JSON per the schema.',
    },
  ];

  const { object } = await generateObject({
    model: anthropic(OPUS_MODEL_ID),
    schema: JUDGEMENT_SCHEMA,
    system: RUBRIC_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userContent }],
    providerOptions: {
      anthropic: {
        // Cache the system prompt (the rubric). Per-clip cost after first
        // call drops from ~$0.015 to ~$0.005. Ephemeral TTL is 5 minutes
        // by default — good enough for batch generation of multiple clips.
        cacheControl: { type: 'ephemeral' },
      },
    },
  });

  return {
    verdict: object.verdict,
    topIssue: object.topIssue ?? undefined,
    criteria: {
      artworkStability: object.criteria.artworkStability,
      compositionStability: object.criteria.compositionStability,
      handAnatomy: object.criteria.handAnatomy,
      colourPersistence: object.criteria.colourPersistence,
      motionPlausibility: object.criteria.motionPlausibility,
      aiGleam: object.criteria.aiGleam,
    },
    judgedAt: new Date().toISOString(),
    model: OPUS_MODEL_ID,
  };
}

/**
 * Pretty-print a judgement for a CLI review flow.
 */
export function formatJudgementForCli(j: BrollJudgement): string {
  const verdictEmoji =
    j.verdict === 'SHIP' ? '✅' : j.verdict === 'ITERATE' ? '⚠️ ' : '❌';
  const lines: string[] = [`${verdictEmoji} Opus verdict: ${j.verdict}`];
  if (j.topIssue) lines.push(`   top issue: ${j.topIssue}`);
  for (const [key, crit] of Object.entries(j.criteria)) {
    const icon = crit.pass ? '✓' : '✗';
    lines.push(`   ${icon} ${key}: ${crit.evidence}`);
  }
  return lines.join('\n');
}
