import type { Meta, StoryObj } from '@storybook/react-vite';
import ProfileAvatar from '@/components/ProfileAvatar/ProfileAvatar';
import { AVATARS } from '@/lib/avatars';

/**
 * Profiles — avatar catalog reference + ProfileAvatar sizing.
 *
 * The full 12-avatar set lives here so a designer can eyeball every
 * illustration at a glance after a generate-profile-avatars.ts run,
 * and a developer can confirm every size variant renders.
 *
 * The CreateProfileModal itself is storied under "05 Modals / Create
 * profile" — it composes ProfileAvatar in its avatar picker, so this
 * file is the lower-level reference, the modal is the composed view.
 */
const meta = {
  title: 'Chunky Crayon/13 Profiles',
  parameters: {
    docs: {
      description: {
        component:
          'Profile avatar catalog + ProfileAvatar sizing reference. The 12 illustrated tiles (9 animals + 3 mythical) are generated by scripts/generate-profile-avatars.ts via gpt-image-2 high; the same recipe family as the Character Builder species tiles.',
      },
    },
  },
} satisfies Meta;

export default meta;
type Story = StoryObj;

const Stage = ({ children }: { children: React.ReactNode }) => (
  <main className="min-h-screen space-y-8 bg-paper p-8">{children}</main>
);

// ─── All 12 avatars ──────────────────────────────────────────────────

export const AvatarCatalog: Story = {
  name: 'Avatar catalog (all 12)',
  render: () => (
    <Stage>
      <section className="space-y-3">
        <div>
          <h2 className="font-tondo text-xl font-bold text-text-primary">
            Profile avatars — 12 tiles
          </h2>
          <p className="text-sm text-text-secondary">
            9 animals + 3 mythical. Tap any to confirm the selected-ring
            affordance (not interactive here, this is the catalog reference).
            The full picker behaviour lives on the CreateProfileModal story.
          </p>
        </div>
        <div className="grid grid-cols-4 gap-4 rounded-3xl border-2 border-paper-cream-dark bg-white p-6 shadow-card sm:grid-cols-6">
          {AVATARS.map((avatar) => (
            <div
              key={avatar.id}
              className="flex flex-col items-center gap-2 text-center"
            >
              <ProfileAvatar
                avatarId={avatar.id}
                name={avatar.name}
                size="lg"
              />
              <span className="font-tondo text-xs font-bold text-text-secondary">
                {avatar.name}
              </span>
            </div>
          ))}
        </div>
      </section>
    </Stage>
  ),
};

// ─── Every size ──────────────────────────────────────────────────────

const SIZES = ['xs', 'sm', 'md', 'lg', 'xl'] as const;

export const AvatarSizes: Story = {
  name: 'ProfileAvatar — every size',
  render: () => (
    <Stage>
      <section className="space-y-3">
        <div>
          <h2 className="font-tondo text-xl font-bold text-text-primary">
            ProfileAvatar — sizes
          </h2>
          <p className="text-sm text-text-secondary">
            Five sizes for header chips, profile cards, hero spots. Same avatar
            (Bunny) at each so the size delta is the only thing that changes.
          </p>
        </div>
        <div className="flex flex-wrap items-end gap-6 rounded-3xl border-2 border-paper-cream-dark bg-white p-6 shadow-card">
          {SIZES.map((size) => (
            <div key={size} className="flex flex-col items-center gap-2">
              <ProfileAvatar avatarId="bunny" name="Bunny" size={size} />
              <span className="font-tondo text-xs font-bold text-text-secondary">
                {size}
              </span>
            </div>
          ))}
        </div>
      </section>
    </Stage>
  ),
};

// ─── Initials fallback ───────────────────────────────────────────────

export const AvatarInitialsFallback: Story = {
  name: 'ProfileAvatar — initials fallback',
  render: () => (
    <Stage>
      <section className="space-y-3">
        <div>
          <h2 className="font-tondo text-xl font-bold text-text-primary">
            Initials fallback
          </h2>
          <p className="text-sm text-text-secondary">
            What ProfileAvatar renders when the catalog has no match (unknown
            id), when the R2 env var isn&apos;t set, or when the image fails to
            load. Grey chip with the name&apos;s initials.
          </p>
        </div>
        <div className="flex flex-wrap items-end gap-6 rounded-3xl border-2 border-paper-cream-dark bg-white p-6 shadow-card">
          {SIZES.map((size) => (
            <div key={size} className="flex flex-col items-center gap-2">
              <ProfileAvatar
                avatarId="unknown-id"
                name="Maya Parent"
                size={size}
              />
              <span className="font-tondo text-xs font-bold text-text-secondary">
                {size}
              </span>
            </div>
          ))}
        </div>
      </section>
    </Stage>
  ),
};
