// import { Metadata } from 'next'; // TODO: Re-enable when generateMetadata is restored
import { notFound } from 'next/navigation';
import {
  getColoringImageById,
  getAllColoringImagesStatic,
} from '@/app/data/coloring-image';
import ColorPalette from '@/components/ColorPalette/ColorPalette';
import ImageCanvas from '@/components/ImageCanvas/ImageCanvas';
import PageWrap from '@/components/PageWrap/PageWrap';
import Breadcrumbs from '@/components/Breadcrumbs';
import SocialShare from '@/components/SocialShare';
import DownloadPDFButton from '@/components/buttons/DownloadPDFButton/DownloadPDFButton';

type ColoringImagePageProps = {
  params: Promise<{
    id: string;
  }>;
};

// Static generation - all coloring image pages are pre-rendered at build time
// Uses WebSocket connections to Neon (not HTTP fetch) which works with prerender
export const generateStaticParams = async () => {
  const images = await getAllColoringImagesStatic();

  return images.map((image) => ({
    id: image.id,
  }));
};

// TODO: Re-enable generateMetadata once Sentry issue is resolved
// Issue: https://github.com/getsentry/sentry-javascript/issues/18392
// generateMetadata breaks cacheComponents when using Turbopack with Sentry
/*
export const generateMetadata = async ({ params }: ColoringImagePageProps): Promise<Metadata | null> => {
  // const coloringImage = await getColoringImage(params);

  // if (!coloringImage) {
  //   return null;
  // }

  // dummy coloring image data
  const coloringImage = {
    title: 'Coloring Image',
    description: 'A coloring image',
    tags: ['coloring', 'image'],
    url: 'https://chunkycrayon.com/images/og-image.jpg',
    alt: 'Coloring Image',
  };

  const title = `${coloringImage.title} - Chunky Crayon`;
  const description =
    `A coloring image featuring: ${coloringImage.description}` ||
    'Coloring book page generated by Chunky Crayon.';
  const keywords =
    coloringImage.tags?.join(',') ||
    'coloring book pages, creative app for kids, personalized coloring pages, educational worksheets, fun learning activities, kids creativity app, interactive coloring app, digital coloring, printable coloring pages, connect the dots, hangman, kids educational games, math worksheets, English worksheets, kids learning tools, creative learning, kids drawing activities, home learning, school learning, web app for kids, iOS app for kids, Android app for kids, Chunky Crayon, fun educational app';

  return {
    title,
    description,
    keywords,
    icons: {
      icon: '/favicon.ico',
      shortcut: '/favicon-16x16.png',
      apple: '/apple-touch-icon.png',
    },
    openGraph: {
      title,
      description,
      url: 'https://chunkycrayon.com',
      siteName: 'Chunky Crayon',
      images: [
        {
          url:
            coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
          width: 1200,
          height: 630,
          alt:
            coloringImage.alt ||
            'Chunky Crayon AI-Generated Coloring Book Pages',
        },
      ],
      locale: 'en-GB',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [
        coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
      ],
    },
  };
};
*/

const ColoringImagePage = async ({ params }: ColoringImagePageProps) => {
  const { id } = await params;
  const coloringImage = await getColoringImageById(id);

  if (!coloringImage) {
    notFound();
  }

  // JSON-LD ImageObject schema for SEO
  const imageSchema = {
    '@context': 'https://schema.org',
    '@type': 'ImageObject',
    '@id': `https://chunkycrayon.com/coloring-image/${id}`,
    name: coloringImage.title || 'Coloring Page',
    description:
      coloringImage.description ||
      'Free printable coloring page from Chunky Crayon',
    contentUrl: coloringImage.svgUrl || coloringImage.url,
    thumbnailUrl: coloringImage.svgUrl || coloringImage.url,
    url: `https://chunkycrayon.com/coloring-image/${id}`,
    isPartOf: {
      '@id': 'https://chunkycrayon.com/#website',
    },
    creator: {
      '@id': 'https://chunkycrayon.com/#organization',
    },
    copyrightHolder: {
      '@id': 'https://chunkycrayon.com/#organization',
    },
    license: 'https://chunkycrayon.com/terms',
    acquireLicensePage: 'https://chunkycrayon.com/pricing',
    keywords:
      coloringImage.tags?.join(', ') || 'coloring page, printable, kids',
  };

  return (
    <PageWrap className="bg-gradient-to-br from-[#FFF2E6] to-[#FFE6CC] flex flex-col gap-y-8">
      {/* ImageObject Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(imageSchema) }}
      />

      {/* Breadcrumbs */}
      <Breadcrumbs
        items={[
          { label: 'Home', href: '/' },
          { label: 'Gallery', href: '/gallery' },
          { label: coloringImage.title || 'Coloring Page' },
        ]}
      />

      <div className="max-w-3xl w-full p-8 bg-crayon-orange rounded-lg shadow-lg self-center">
        <div className="flex flex-col items-center text-center mb-8">
          <h1 className="font-dyna-puff text-5xl font-bold mb-2 text-white">
            {coloringImage.title}
          </h1>
          <div className="flex items-center gap-x-2 text-lg text-white font-medium mb-4">
            by Chunky Crayon
          </div>
          <SocialShare
            url={`https://chunkycrayon.com/coloring-image/${id}`}
            title={coloringImage.title || 'Coloring Page'}
            description={
              coloringImage.description ||
              'Free printable coloring page from Chunky Crayon'
            }
            imageUrl={coloringImage.svgUrl || coloringImage.url || undefined}
            className="bg-white/20 px-4 py-2 rounded-full"
          />
        </div>
        <div className="flex flex-col gap-y-4">
          <ColorPalette className="self-center" />
          <ImageCanvas
            coloringImage={coloringImage}
            className="rounded-lg shadow-lg bg-white overflow-hidden"
          />
          <DownloadPDFButton
            coloringImage={coloringImage}
            className="self-center"
          />
        </div>
      </div>
    </PageWrap>
  );
};

export default ColoringImagePage;
