// import { Metadata } from 'next'; // TODO: Re-enable when generateMetadata is restored
import { notFound } from 'next/navigation';
import {
  getColoringImageById,
  getAllColoringImagesStatic,
} from '@/app/data/coloring-image';
import ColorPalette from '@/components/ColorPalette/ColorPalette';
import ImageCanvas from '@/components/ImageCanvas/ImageCanvas';
import PageWrap from '@/components/PageWrap/PageWrap';
import DownloadPDFButton from '@/components/buttons/DownloadPDFButton/DownloadPDFButton';

type ColoringImagePageProps = {
  params: Promise<{
    id: string;
  }>;
};

// Static generation - all coloring image pages are pre-rendered at build time
// Uses WebSocket connections to Neon (not HTTP fetch) which works with prerender
export const generateStaticParams = async () => {
  const images = await getAllColoringImagesStatic();

  return images.map((image) => ({
    id: image.id,
  }));
};

// TODO: Re-enable generateMetadata once Sentry issue is resolved
// Issue: https://github.com/getsentry/sentry-javascript/issues/18392
// generateMetadata breaks cacheComponents when using Turbopack with Sentry
/*
export const generateMetadata = async ({ params }: ColoringImagePageProps): Promise<Metadata | null> => {
  // const coloringImage = await getColoringImage(params);

  // if (!coloringImage) {
  //   return null;
  // }

  // dummy coloring image data
  const coloringImage = {
    title: 'Coloring Image',
    description: 'A coloring image',
    tags: ['coloring', 'image'],
    url: 'https://chunkycrayon.com/images/og-image.jpg',
    alt: 'Coloring Image',
  };

  const title = `${coloringImage.title} - Chunky Crayon`;
  const description =
    `A colouring image featuring: ${coloringImage.description}` ||
    'Colouring book page generated by Chunky Crayon.';
  const keywords =
    coloringImage.tags?.join(',') ||
    'colouring book pages, creative app for kids, personalized colouring pages, educational worksheets, fun learning activities, kids creativity app, interactive colouring app, digital colouring, printable colouring pages, connect the dots, hangman, kids educational games, math worksheets, English worksheets, kids learning tools, creative learning, kids drawing activities, home learning, school learning, web app for kids, iOS app for kids, Android app for kids, Chunky Crayon, fun educational app';

  return {
    title,
    description,
    keywords,
    icons: {
      icon: '/favicon.ico',
      shortcut: '/favicon-16x16.png',
      apple: '/apple-touch-icon.png',
    },
    openGraph: {
      title,
      description,
      url: 'https://chunkycrayon.com',
      siteName: 'Chunky Crayon',
      images: [
        {
          url:
            coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
          width: 1200,
          height: 630,
          alt:
            coloringImage.alt ||
            'Chunky Crayon AI-Generated Colouring Book Pages',
        },
      ],
      locale: 'en-GB',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [
        coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
      ],
    },
  };
};
*/

const ColoringImagePage = async ({ params }: ColoringImagePageProps) => {
  const { id } = await params;
  const coloringImage = await getColoringImageById(id);

  if (!coloringImage) {
    notFound();
  }

  return (
    <PageWrap className="bg-gradient-to-br from-[#FFF2E6] to-[#FFE6CC] flex justify-center items-center gap-y-32">
      <div className="max-w-3xl w-full p-8 bg-[#FF8A65] rounded-lg shadow-lg">
        <div className="flex flex-col items-center text-center mb-8">
          <h1 className="font-dyna-puff text-5xl font-bold mb-2 text-white">
            {coloringImage.title}
          </h1>
          <div className="flex items-center gap-x-2 text-lg text-white font-medium">
            by Chunky Crayon
          </div>
        </div>
        <div className="flex flex-col gap-y-4">
          <ColorPalette className="self-center" />
          <ImageCanvas
            coloringImage={coloringImage}
            className="rounded-lg shadow-lg bg-white overflow-hidden"
          />
          <DownloadPDFButton
            coloringImage={coloringImage}
            className="self-center"
          />
        </div>
      </div>
    </PageWrap>
  );
};

export default ColoringImagePage;
