// import { Metadata } from 'next'; // TODO: Re-enable when generateMetadata is restored
import { notFound } from 'next/navigation';
import {
  getColoringImageById,
  getAllColoringImagesStatic,
} from '@/app/data/coloring-image';
import { auth } from '@/auth';
import ColoringArea from '@/components/ColoringArea/ColoringArea';
import PageWrap from '@/components/PageWrap/PageWrap';
import Breadcrumbs from '@/components/Breadcrumbs';

type ColoringImagePageProps = {
  params: Promise<{
    id: string;
  }>;
};

// Static generation - all coloring image pages are pre-rendered at build time
// Uses WebSocket connections to Neon (not HTTP fetch) which works with prerender
export const generateStaticParams = async () => {
  const images = await getAllColoringImagesStatic();

  return images.map((image) => ({
    id: image.id,
  }));
};

// TODO: Re-enable generateMetadata once Sentry issue is resolved
// Issue: https://github.com/getsentry/sentry-javascript/issues/18392
// generateMetadata breaks cacheComponents when using Turbopack with Sentry
/*
export const generateMetadata = async ({ params }: ColoringImagePageProps): Promise<Metadata | null> => {
  // const coloringImage = await getColoringImage(params);

  // if (!coloringImage) {
  //   return null;
  // }

  // dummy coloring image data
  const coloringImage = {
    title: 'Coloring Image',
    description: 'A coloring image',
    tags: ['coloring', 'image'],
    url: 'https://chunkycrayon.com/images/og-image.jpg',
    alt: 'Coloring Image',
  };

  const title = `${coloringImage.title} - Chunky Crayon`;
  const description =
    `A coloring image featuring: ${coloringImage.description}` ||
    'Coloring book page generated by Chunky Crayon.';
  const keywords =
    coloringImage.tags?.join(',') ||
    'coloring book pages, creative app for kids, personalized coloring pages, educational worksheets, fun learning activities, kids creativity app, interactive coloring app, digital coloring, printable coloring pages, connect the dots, hangman, kids educational games, math worksheets, English worksheets, kids learning tools, creative learning, kids drawing activities, home learning, school learning, web app for kids, iOS app for kids, Android app for kids, Chunky Crayon, fun educational app';

  return {
    title,
    description,
    keywords,
    icons: {
      icon: '/favicon.ico',
      shortcut: '/favicon-16x16.png',
      apple: '/apple-touch-icon.png',
    },
    openGraph: {
      title,
      description,
      url: 'https://chunkycrayon.com',
      siteName: 'Chunky Crayon',
      images: [
        {
          url:
            coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
          width: 1200,
          height: 630,
          alt:
            coloringImage.alt ||
            'Chunky Crayon AI-Generated Coloring Book Pages',
        },
      ],
      locale: 'en-GB',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [
        coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
      ],
    },
  };
};
*/

const ColoringImagePage = async ({ params }: ColoringImagePageProps) => {
  const { id } = await params;
  const [coloringImage, session] = await Promise.all([
    getColoringImageById(id),
    auth(),
  ]);

  if (!coloringImage) {
    notFound();
  }

  const isAuthenticated = !!session?.user?.id;

  // JSON-LD ImageObject schema for SEO
  const imageSchema = {
    '@context': 'https://schema.org',
    '@type': 'ImageObject',
    '@id': `https://chunkycrayon.com/coloring-image/${id}`,
    name: coloringImage.title || 'Coloring Page',
    description:
      coloringImage.description ||
      'Free printable coloring page from Chunky Crayon',
    contentUrl: coloringImage.svgUrl || coloringImage.url,
    thumbnailUrl: coloringImage.svgUrl || coloringImage.url,
    url: `https://chunkycrayon.com/coloring-image/${id}`,
    isPartOf: {
      '@id': 'https://chunkycrayon.com/#website',
    },
    creator: {
      '@id': 'https://chunkycrayon.com/#organization',
    },
    copyrightHolder: {
      '@id': 'https://chunkycrayon.com/#organization',
    },
    license: 'https://chunkycrayon.com/terms',
    acquireLicensePage: 'https://chunkycrayon.com/pricing',
    keywords:
      coloringImage.tags?.join(', ') || 'coloring page, printable, kids',
  };

  return (
    <PageWrap className="flex flex-col gap-y-6">
      {/* ImageObject Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(imageSchema) }}
      />

      {/* Breadcrumbs */}
      <Breadcrumbs
        items={[
          { label: 'Home', href: '/' },
          { label: 'Gallery', href: '/gallery' },
          { label: coloringImage.title || 'Coloring Page' },
        ]}
      />

      {/* Title - clean and minimal */}
      <h1 className="font-tondo font-bold text-2xl md:text-3xl text-text-primary text-center">
        {coloringImage.title}
      </h1>

      {/* Coloring Area - clean white card matching gallery aesthetic */}
      <div className="max-w-3xl w-full mx-auto">
        <div className="bg-white rounded-2xl border-2 border-paper-cream-dark p-4 md:p-6 shadow-sm">
          <ColoringArea
            coloringImage={coloringImage}
            isAuthenticated={isAuthenticated}
          />
        </div>
      </div>
    </PageWrap>
  );
};

export default ColoringImagePage;
