import { ExpoConfig, ConfigContext } from "expo/config";
import {
  withGradleProperties,
  withAndroidManifest,
  ConfigPlugin,
} from "expo/config-plugins";
import { existsSync } from "fs";
import { join } from "path";
import pkg from "./package.json";

// Bump the Gradle daemon heap so the D8 dex-merge step (:app:mergeExtDexDebug)
// doesn't OOM. The Expo-generated android/gradle.properties ships
// `org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m`, and 2 GiB isn't
// enough to merge our native-dep set (Skia, Expo modules, RevenueCat, FB SDK,
// Amazon appstore SDK, ...) — the build dies with `D8: OutOfMemoryError: Java
// heap space`. android/ is gitignored and fully regenerated by
// `expo prebuild --clean`, so this can't live as a hand-edit there; it has to
// be a config plugin that re-applies on every prebuild.
const GRADLE_JVMARGS = "-Xmx6144m -XX:MaxMetaspaceSize=1024m";

const withGradleHeap: ConfigPlugin = (config) =>
  withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === "org.gradle.jvmargs",
    );
    if (existing && existing.type === "property") {
      existing.value = GRADLE_JVMARGS;
    } else {
      cfg.modResults.push({
        type: "property",
        key: "org.gradle.jvmargs",
        value: GRADLE_JVMARGS,
      });
    }
    return cfg;
  });

// expo-sensors hardcodes <uses-permission ACTIVITY_RECOGNITION> in its own
// library manifest, which merges into our AAB even though we only use the
// Accelerometer (useUpsideDownHint.ts) and never the Pedometer (the only API
// that needs it). The stray permission makes Google Play force a "Health apps"
// declaration on a coloring app and reads as over-permissioning under Designed
// for Families. The plugin's motionPermission:false option is iOS-only, so strip
// it on Android via a manifest-merger removal node. android/ is regenerated by
// prebuild, so this must be a config plugin, not a hand-edit.
const withRemoveActivityRecognition: ConfigPlugin = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    // Ensure the tools namespace is declared so tools:node is honored.
    manifest.$ = manifest.$ || {};
    if (!manifest.$["xmlns:tools"]) {
      manifest.$["xmlns:tools"] = "http://schemas.android.com/tools";
    }
    manifest["uses-permission"] = manifest["uses-permission"] || [];
    const NAME = "android.permission.ACTIVITY_RECOGNITION";
    const already = manifest["uses-permission"].some(
      (p) => p.$?.["android:name"] === NAME && p.$?.["tools:node"] === "remove",
    );
    if (!already) {
      manifest["uses-permission"].push({
        $: {
          "android:name": NAME,
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          "tools:node": "remove",
        } as any,
      });
    }
    return cfg;
  });

export default ({ config }: ConfigContext): ExpoConfig => {
  // Reverse the Google iOS Client ID (from xxx.apps.googleusercontent.com to com.googleusercontent.apps.xxx)
  const googleIosClientId = process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
    ? process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID.split(".")
        .reverse()
        .join(".")
    : "";

  // Facebook Login was removed before store submission: the Meta SDK
  // (react-native-fbsdk-next → facebook-core) injects the AD_ID permission into
  // the Android manifest, which conflicts with Google Play's Designed for
  // Families program (no advertising id) and forces a dishonest "uses ad id"
  // declaration on a zero-ads kids app. FB login is feature-flag-gated off and
  // wasn't shipping at launch, so the dependency + native plugin are dropped
  // entirely. Re-add the plugin here (gated on EXPO_PUBLIC_FACEBOOK_* env) if FB
  // login is ever brought back — but reassess the Families AD_ID implication
  // first. See project_cc_mobile_store_submission.

  // Per-variant app identity (matches PTP). EXPO_PUBLIC_ENVIRONMENT is set per
  // EAS build profile (eas.json) so dev / preview / prod produce DIFFERENT
  // bundle ids + names + icons and can all install side-by-side on one device.
  // Prod keeps the original com.chewybytes.chunkycrayon.app + "Chunky Crayon"
  // (the live App Store identity — do NOT change). dev/preview get suffixed ids.
  const env = process.env.EXPO_PUBLIC_ENVIRONMENT || "development";

  const appName =
    env === "production"
      ? "Chunky Crayon"
      : env === "preview"
        ? "CC Internal"
        : "CC Dev";

  const bundleId =
    env === "production"
      ? "com.chewybytes.chunkycrayon.app"
      : env === "preview"
        ? "com.chewybytes.chunkycrayon.app.internal"
        : "com.chewybytes.chunkycrayon.app.dev";

  // Per-variant icons if present, else fall back to the prod icon. CC doesn't
  // ship dev/preview-badged icons yet — drop in icon-preview.png / icon-dev.png
  // + adaptive-icon-{preview,dev}.png later and they're picked up automatically
  // (no config change). The existsSync guard means a missing badged icon never
  // breaks a dev/preview build; it just shares the prod icon until then.
  const variantSuffix =
    env === "production" ? "" : env === "preview" ? "-preview" : "-dev";
  const pickIcon = (base: string): string => {
    const variantPath = `./assets/images/${base}${variantSuffix}.png`;
    return existsSync(join(__dirname, variantPath))
      ? variantPath
      : `./assets/images/${base}.png`;
  };
  const icon = pickIcon("icon");
  const adaptiveIcon = pickIcon("adaptive-icon");

  const expoConfig: ExpoConfig = {
    ...config,
    name: appName,
    slug: "chunky-crayon",
    owner: "chewybytes",
    version: pkg.version,
    orientation: "default",
    icon,
    scheme: "chunkycrayon",
    userInterfaceStyle: "light",
    ios: {
      supportsTablet: true,
      // requireFullScreen must be FALSE for the iPad to actually rotate.
      // With requireFullScreen=true (multitasking disabled) AND no
      // UIApplicationSceneManifest, the scene-less Expo SDK 56 window resizes
      // its RN root to the landscape size (useWindowDimensions reports
      // 1376x1032) but the WINDOW's display surface never completes the
      // rotation — so the correct landscape layout is painted into a portrait
      // surface and shown sideways. Allowing multitasking (requireFullScreen
      // false) lets iPadOS treat the app as a normal resizable window that
      // rotates natively with the device. Verified on iPad Pro 13.
      //
      // DO NOT add a UIApplicationSceneManifest here. The Expo SDK 56
      // AppDelegate.swift uses the classic non-scene UIWindow lifecycle
      // (creates `window` in didFinishLaunchingWithOptions and attaches the RN
      // root via startReactNative(...in: window)). Declaring a scene manifest
      // without a matching UISceneDelegate switches iOS to scene-based window
      // management, orphaning the AppDelegate's window — the RN root never gets
      // a visible window and the app boots to a BLACK SCREEN on every device.
      requireFullScreen: false,
      bundleIdentifier: bundleId,
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
        CFBundleURLTypes: [
          {
            CFBundleURLSchemes: [googleIosClientId],
          },
        ],
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: adaptiveIcon,
        backgroundColor: "#FF9F6E",
      },
      package: bundleId,
    },
    web: {
      bundler: "metro",
      output: "static",
      favicon: "./assets/images/favicon.png",
    },
    plugins: [
      "expo-router",
      // Wires the ScreenOrientation AppDelegate subscriber + react-delegate
      // handler so the scene-less Expo SDK 56 window can be told to follow
      // device rotation (unlockAsync at the app root drives it). This is the
      // scene-compatible way to get real iPad landscape WITHOUT a
      // UIApplicationSceneManifest (which black-screens this app — see the ios
      // block above).
      "expo-screen-orientation",
      [
        "expo-splash-screen",
        {
          image: "./assets/images/splash-icon.png",
          imageWidth: 200,
          resizeMode: "contain",
          backgroundColor: "#FF9F6E",
        },
      ],
      "expo-dev-client",
      "expo-font",
      "expo-web-browser",
      "expo-audio",
      "expo-apple-authentication",
      "expo-secure-store",
      "expo-sharing",
      "expo-status-bar",
      "expo-image",
      "expo-localization",
      "@react-native-google-signin/google-signin",
      [
        "expo-image-picker",
        {
          cameraPermission:
            "Allow Chunky Crayon to take photos of your hand-drawn sketches",
          photosPermission:
            "Allow Chunky Crayon to access your photos to select sketches",
        },
      ],
      // expo-media-library auto-links with the default granular permission set
      // ['photo','video','audio'], which adds READ_MEDIA_VIDEO + READ_MEDIA_AUDIO
      // to the Android manifest. We only ever read/save IMAGES (pick a photo to
      // colorize + save finished artwork to the gallery), never video or audio.
      // Declaring unused media permissions is a Designed-for-Families review flag,
      // so restrict the plugin to ['photo'] — drops READ_MEDIA_VIDEO/AUDIO from the
      // merged manifest, leaving only READ_MEDIA_IMAGES (the one we actually use).
      [
        "expo-media-library",
        {
          granularPermissions: ["photo"],
        },
      ],
      [
        "@sentry/react-native",
        {
          url: "https://sentry.io/",
          project: "chunky-crayon-app",
          organization: "chewybytes",
        },
      ],
      [
        "expo-speech-recognition",
        {
          microphonePermission:
            "Allow Chunky Crayon to use the microphone to hear your coloring ideas",
          speechRecognitionPermission:
            "Allow Chunky Crayon to recognize your voice to create coloring pages",
        },
      ],
      // Pin the Android SDK levels Expo already generates. The Gradle daemon
      // heap bump (so the dex merge doesn't OOM) is applied separately via the
      // withGradleHeap plugin on the returned config below — expo-build-properties
      // has no field for org.gradle.jvmargs, and the static `plugins` array only
      // accepts string/tuple entries, not a bare ConfigPlugin function.
      [
        "expo-build-properties",
        {
          android: {
            compileSdkVersion: 36,
            targetSdkVersion: 36,
            buildToolsVersion: "36.0.0",
          },
        },
      ],
    ],
    experiments: { typedRoutes: true },
    updates: { url: "https://u.expo.dev/b57fff00-94cc-43fb-9224-924e34d301c9" },
    runtimeVersion: { policy: "appVersion" },
    extra: { eas: { projectId: "7cae64a2-e46f-4be2-880b-4e51c4f33036" } },
  };

  // Apply the function-form plugins to the assembled config. They're applied
  // here rather than in the `plugins` array because that array's type only
  // accepts string/tuple entries, not a bare ConfigPlugin.
  return withRemoveActivityRecognition(
    withGradleHeap(expoConfig),
  ) as ExpoConfig;
};
