import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBalloons,
  faRocketLaunch,
  faFish,
  faTreePalm,
} from "@fortawesome/pro-duotone-svg-icons";
import { CRAYON } from "@/lib/design";

/**
 * Onboarding welcome-scene catalog — the single source of truth for the
 * coloring slide's scene switcher.
 *
 * Each scene is a bundled coloring SVG (Colo the crayon mascot starring in a
 * different world) + its bundled REGION STORE (the modern Magic Brush / Auto
 * Color data — a gzipped pixel→region-id map + regionsJson with one realistic
 * palette per region). Generated by `scripts/generate-onboarding-scenes.ts`
 * (line art) and `scripts/generate-onboarding-region-stores.ts` (region store).
 *
 * Region data is bundled (offline first-run); the slide resolves the `.bin`
 * asset to a file:// URI and feeds it to the canvas as `regionMapUrl`, so the
 * real `useRegionStore` powers both magic tools natively.
 *
 * Adding a scene = generate its SVG + region store, drop the assets in, add one
 * entry here.
 */

// regionsJson shape (realistic-only) bundled per scene. Mirrors the subset of
// RegionStoreJson the canvas's useRegionStore consumes.
export type OnboardingRegionData = {
  regionMapWidth: number;
  regionMapHeight: number;
  regionsJson: {
    sceneDescription?: string;
    sourceWidth: number;
    sourceHeight: number;
    regions: Array<{
      id: number;
      bounds: { x: number; y: number; width: number; height: number };
      centroid: { x: number; y: number };
      pixelCount: number;
      label: string;
      objectGroup: string;
      palettes: { realistic: { hex: string; colorName: string } };
    }>;
  };
};

export type OnboardingScene = {
  /** Stable id — also the canvas imageId (must start with "onboarding-" so the
   *  canvas-sync layer treats it as local-only; see isLocalOnlyImage). */
  id: string;
  /** a11y label only (the picker is label-FREE — icons, no visible text). */
  label: string;
  /** Bundled coloring SVG asset module (require() → numeric module id in RN). */
  svg: number;
  /** Bundled gzipped region-map asset module (the .bin). Resolved to a file://
   *  URI at runtime and passed as the canvas's regionMapUrl. */
  regionMap: number;
  /** Bundled region metadata (.json: dims + realistic-only regionsJson). */
  regionData: OnboardingRegionData;
  /** Scene-picker icon (FA duotone) + its crayon tint — no text, kid-friendly. */
  icon: IconDefinition;
  iconPrimary: string;
  iconSecondary: string;
};

// All scenes are 1024x1024 (the SVG viewBox + the region-map coordinate space).
export const ONBOARDING_SCENE_SIZE = 1024;

/* eslint-disable @typescript-eslint/no-require-imports */
export const ONBOARDING_SCENES: readonly OnboardingScene[] = [
  {
    id: "onboarding-party",
    label: "Party",
    svg: require("@/assets/onboarding/welcome-party.svg"),
    regionMap: require("@/assets/onboarding/regions/welcome-party.bin"),
    regionData: require("@/assets/onboarding/regions/welcome-party.json"),
    icon: faBalloons,
    iconPrimary: CRAYON.orange.base,
    iconSecondary: CRAYON.yellow.base,
  },
  {
    id: "onboarding-space",
    label: "Space",
    svg: require("@/assets/onboarding/welcome-space.svg"),
    regionMap: require("@/assets/onboarding/regions/welcome-space.bin"),
    regionData: require("@/assets/onboarding/regions/welcome-space.json"),
    icon: faRocketLaunch,
    iconPrimary: CRAYON.blue.base,
    iconSecondary: CRAYON.purple.light,
  },
  {
    id: "onboarding-underwater",
    label: "Under the Sea",
    svg: require("@/assets/onboarding/welcome-underwater.svg"),
    regionMap: require("@/assets/onboarding/regions/welcome-underwater.bin"),
    regionData: require("@/assets/onboarding/regions/welcome-underwater.json"),
    icon: faFish,
    iconPrimary: CRAYON.blue.base,
    iconSecondary: CRAYON.green.light,
  },
  {
    id: "onboarding-jungle",
    label: "Jungle",
    svg: require("@/assets/onboarding/welcome-jungle.svg"),
    regionMap: require("@/assets/onboarding/regions/welcome-jungle.bin"),
    regionData: require("@/assets/onboarding/regions/welcome-jungle.json"),
    icon: faTreePalm,
    iconPrimary: CRAYON.green.base,
    iconSecondary: CRAYON.green.light,
  },
] as const;
/* eslint-enable @typescript-eslint/no-require-imports */
