/**
 * Copy the 4 v1 beginner references that pass the audit (dinosaur,
 * family-and-friends, farm-animals, trains) to the new v2/beginner/
 * directory so the v2/beginner/ set ends up with exactly 8 images
 * matching the same 8 subjects as v2/intermediate/ and v2/advanced/.
 *
 * The remaining 4 beginners (birthdays, sea-creatures, superheroes,
 * unicorns) are regenerated by scripts/generate-v2-references.ts —
 * they failed the audit because of complexity creep (or in the case
 * of superheroes, the Superman S logo).
 *
 * v1 originals stay at their current R2 paths as the de facto backup.
 *
 * Usage: pnpm tsx scripts/copy-beginner-references-to-v2.ts
 * Env: R2_ENDPOINT, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET,
 *      R2_PUBLIC_URL
 */

import { put } from '@one-colored-pixel/storage';

const V1_SOURCES = {
  dinosaur:
    'https://assets.chunkycrayon.com/reference-images/dinosaur-bfmBtp1o0kVeIZtuVVNhmKTMJXOgS7.webp',
  'family-and-friends':
    'https://assets.chunkycrayon.com/reference-images/family-and-friends-g4vlGFNcWXrcHQ7sB4y8LLYiO3PIAG.webp',
  'farm-animals':
    'https://assets.chunkycrayon.com/reference-images/farm-animals-knAdbOJKhulPhb7xnaCkMXycTunbNi.webp',
  trains:
    'https://assets.chunkycrayon.com/reference-images/trains-TOkt3DJ3Oy56ZTV0uy7h2XmD8DsTGV.webp',
} as const;

async function copy(subject: string, sourceUrl: string) {
  console.log(`[copy] ${subject} <- ${sourceUrl}`);
  const res = await fetch(sourceUrl);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${sourceUrl}: ${res.status}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  const r2Path = `reference-images/v2/beginner/${subject}.webp`;
  const { url } = await put(r2Path, buf, {
    access: 'public',
    contentType: 'image/webp',
    allowOverwrite: true,
  });
  console.log(`[copy] ${subject} -> ${url}`);
}

async function main() {
  for (const [subject, source] of Object.entries(V1_SOURCES)) {
    await copy(subject, source);
  }
  console.log('[copy] done');
}

main().catch((err) => {
  console.error('[copy] fatal:', err);
  process.exit(1);
});
