#!/usr/bin/env tsx

/**
 * Data migration: move WEEKLY/MONTHLY rows and the 3 ad coloring images
 * to the new `SYSTEM` generationType + purposeKey + showInCommunity
 * shape. Runs between the additive schema migration (which added SYSTEM,
 * purposeKey, showInCommunity) and the destructive schema migration
 * (which drops WEEKLY/MONTHLY).
 *
 * Idempotent: safe to re-run. Uses Prisma client (not raw SQL) so it
 * respects the current schema and types.
 *
 * Usage (must use `tsx -r dotenv/config` pre-load because
 * @one-colored-pixel/db reads DATABASE_URL at module init):
 *
 *   # Dev
 *   DOTENV_CONFIG_PATH=.env.local \
 *     pnpm tsx -r dotenv/config scripts/migrate-to-system-generation-type.ts --dry-run
 *   DOTENV_CONFIG_PATH=.env.local \
 *     pnpm tsx -r dotenv/config scripts/migrate-to-system-generation-type.ts
 *
 *   # Prod — after CI deploys the additive migration
 *   vercel env pull /tmp/p.env --environment=production
 *   DATABASE_URL=$(grep '^DATABASE_URL=' /tmp/p.env | cut -d= -f2- | tr -d '"') \
 *     pnpm tsx scripts/migrate-to-system-generation-type.ts
 *   rm /tmp/p.env
 */

import { db, GenerationType } from '@one-colored-pixel/db';
import { adPurposeKey } from '../lib/coloring-image-purpose';

// WEEKLY/MONTHLY are retired in the same PR sequence as this script —
// additive migration adds SYSTEM, this script runs, destructive
// migration drops WEEKLY/MONTHLY. Between those three steps the enum
// type no longer declares these values, so we cast. At runtime the
// Postgres enum still contains them (the destructive migration hasn't
// run yet), so the underlying queries succeed.
const RETIRED_WEEKLY = 'WEEKLY' as unknown as GenerationType;
const RETIRED_MONTHLY = 'MONTHLY' as unknown as GenerationType;

// Ad coloring image IDs — these are the three images generated by
// generate-ad-assets.ts for the T-rex / Foxes / Dragon campaigns.
// Hardcoded because they're small, stable, and both dev + prod have
// them at these exact IDs after scripts/backfill-ad-images-to-prod.ts.
const AD_IDS: Record<string, string> = {
  cmo8hw3o40000z36l46efmnwe: 'trex',
  cmo8hxg6u0001z36lo1tk80bq: 'foxes',
  cmo8hypn80002z36lrab18enu: 'dragon',
};

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  if (dryRun) console.log('🧪 dry-run: no writes will occur\n');

  // Log where we're about to write — matters because this script can
  // target dev or prod depending on DATABASE_URL.
  const dbHost = (process.env.DATABASE_URL ?? '').match(/@([^/]+)/)?.[1];
  console.log(`🗄  database host: ${dbHost ?? '(unknown)'}\n`);

  // -----------------------------------------------------------------
  // 1. Ad images → SYSTEM + ad:<campaign> + hidden from community
  // -----------------------------------------------------------------
  for (const [id, campaignKey] of Object.entries(AD_IDS)) {
    const existing = await db.coloringImage.findUnique({
      where: { id },
      select: {
        id: true,
        generationType: true,
        purposeKey: true,
        showInCommunity: true,
      },
    });

    if (!existing) {
      console.log(`⏭  ad image ${id} (${campaignKey}) not found — skip`);
      continue;
    }

    const targetPurposeKey = adPurposeKey(campaignKey);
    const alreadyCorrect =
      existing.generationType === GenerationType.SYSTEM &&
      existing.purposeKey === targetPurposeKey &&
      existing.showInCommunity === false;

    if (alreadyCorrect) {
      console.log(`⏭  ad image ${id} (${campaignKey}) already SYSTEM — skip`);
      continue;
    }

    if (dryRun) {
      console.log(
        `[dry-run] would set ad image ${id} (${campaignKey}) → SYSTEM + ${targetPurposeKey} + showInCommunity=false`,
      );
      continue;
    }

    await db.coloringImage.update({
      where: { id },
      data: {
        generationType: GenerationType.SYSTEM,
        purposeKey: targetPurposeKey,
        showInCommunity: false,
      },
    });
    console.log(
      `✅ ad image ${id} (${campaignKey}) → SYSTEM + ${targetPurposeKey}`,
    );
  }

  // -----------------------------------------------------------------
  // 2. Legacy WEEKLY rows → SYSTEM + legacy-weekly (community visible)
  // -----------------------------------------------------------------
  const weeklyWhere = { generationType: RETIRED_WEEKLY };
  const weeklyCount = await db.coloringImage.count({ where: weeklyWhere });
  if (weeklyCount === 0) {
    console.log('\n⏭  no WEEKLY rows to migrate');
  } else if (dryRun) {
    console.log(
      `\n[dry-run] would move ${weeklyCount} WEEKLY row(s) → SYSTEM + 'legacy-weekly'`,
    );
  } else {
    const res = await db.coloringImage.updateMany({
      where: weeklyWhere,
      data: {
        generationType: GenerationType.SYSTEM,
        purposeKey: 'legacy-weekly',
      },
    });
    console.log(
      `\n✅ migrated ${res.count} WEEKLY row(s) → SYSTEM + 'legacy-weekly'`,
    );
  }

  // -----------------------------------------------------------------
  // 3. Legacy MONTHLY rows → SYSTEM + legacy-monthly (community visible)
  // -----------------------------------------------------------------
  const monthlyWhere = { generationType: RETIRED_MONTHLY };
  const monthlyCount = await db.coloringImage.count({ where: monthlyWhere });
  if (monthlyCount === 0) {
    console.log('⏭  no MONTHLY rows to migrate');
  } else if (dryRun) {
    console.log(
      `[dry-run] would move ${monthlyCount} MONTHLY row(s) → SYSTEM + 'legacy-monthly'`,
    );
  } else {
    const res = await db.coloringImage.updateMany({
      where: monthlyWhere,
      data: {
        generationType: GenerationType.SYSTEM,
        purposeKey: 'legacy-monthly',
      },
    });
    console.log(
      `✅ migrated ${res.count} MONTHLY row(s) → SYSTEM + 'legacy-monthly'`,
    );
  }

  // -----------------------------------------------------------------
  // Final sanity check
  // -----------------------------------------------------------------
  const remaining = await db.coloringImage.count({
    where: {
      generationType: { in: [RETIRED_WEEKLY, RETIRED_MONTHLY] },
    },
  });
  if (remaining > 0 && !dryRun) {
    throw new Error(
      `expected zero WEEKLY/MONTHLY rows after migration, found ${remaining}`,
    );
  }

  console.log('\n✨ done');
  await db.$disconnect();
}

main().catch(async (err) => {
  console.error('❌ data migration failed:', err);
  await db.$disconnect();
  process.exit(1);
});
