/**
 * One-time pass over all Character Builder species / trait / voice
 * thumbnails — strip the opaque white background via Replicate's
 * 851-labs/background-remover so the tinted SceneTile background
 * shows through cleanly instead of being hidden behind a white square.
 *
 * Same `feedback_always_transparent_pngs` motivation as the avatar
 * pipeline. Character thumbnails were generated by
 * `scripts/generate-character-thumbnails.ts` via gpt-image-2 (which
 * rejects `background:'transparent'`), so they shipped opaque RGB.
 *
 * Cost: ~$0.0004/image × ~24 entries = ~$0.01. Total runtime ~1 min.
 *
 * Usage (from apps/chunky-crayon-web):
 *   pnpm tsx -r dotenv/config scripts/remove-character-thumbnail-backgrounds.ts \
 *     dotenv_config_path=.env.local
 *
 *   # subset:
 *   pnpm tsx -r dotenv/config scripts/remove-character-thumbnail-backgrounds.ts \
 *     --only=species dotenv_config_path=.env.local
 */

import { put, exists } from '@one-colored-pixel/storage';
import {
  SPECIES_OPTIONS,
  TRAIT_OPTIONS,
  VOICE_TILES,
} from '../lib/characters/picker-catalog';
import { removeBackground } from '../lib/replicate-bg-remove';

const args = process.argv.slice(2);
const ONLY = args
  .find((a) => a.startsWith('--only='))
  ?.split('=')[1]
  ?.trim() as 'species' | 'trait' | 'voice' | undefined;
const FORCE = args.includes('--force');

const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL;
if (!R2_PUBLIC_URL) throw new Error('R2_PUBLIC_URL not set');

type Job = { kind: 'species' | 'trait' | 'voice'; id: string; key: string };

const buildJobs = (): Job[] => {
  const all: Job[] = [];
  for (const s of SPECIES_OPTIONS) {
    if (s.thumbnailKey) {
      all.push({ kind: 'species', id: s.key, key: s.thumbnailKey });
    }
  }
  for (const t of TRAIT_OPTIONS) {
    if (t.thumbnailKey) {
      all.push({ kind: 'trait', id: t.key, key: t.thumbnailKey });
    }
  }
  for (const v of VOICE_TILES) {
    if (v.thumbnailKey) {
      all.push({ kind: 'voice', id: v.key, key: v.thumbnailKey });
    }
  }
  return all;
};

// Sentinel R2 key we append to the original to mark "this has been
// bg-stripped already." Avoids re-billing on every run. Cleared by
// passing --force.
const stripMarkerKey = (key: string) => `${key}.stripped`;

const main = async () => {
  const jobs = buildJobs().filter((j) => !ONLY || j.kind === ONLY);
  console.log(`[char-bg-rm] ${jobs.length} thumbnails to process`);

  let stripped = 0;
  let skipped = 0;
  let failed = 0;

  for (const job of jobs) {
    const marker = stripMarkerKey(job.key);
    if (!FORCE && (await exists(marker))) {
      console.log(`[char-bg-rm] skip ${job.kind}:${job.id} (already stripped)`);
      skipped += 1;
      continue;
    }

    try {
      const start = Date.now();
      const publicUrl = `${R2_PUBLIC_URL}/${job.key}?t=${Date.now()}`;
      const rgbaBuf = await removeBackground(publicUrl);
      await put(job.key, rgbaBuf, {
        contentType: 'image/png',
        allowOverwrite: true,
      });
      // Write the marker so subsequent runs skip cleanly.
      await put(marker, Buffer.from(''), {
        contentType: 'text/plain',
        allowOverwrite: true,
      });
      const elapsed = ((Date.now() - start) / 1000).toFixed(1);
      console.log(
        `[char-bg-rm] ${job.kind}:${job.id} ${elapsed}s -> ${(rgbaBuf.length / 1024).toFixed(0)}KB RGBA`,
      );
      stripped += 1;
    } catch (err) {
      console.error(`[char-bg-rm] ${job.kind}:${job.id} FAILED:`, err);
      failed += 1;
    }
  }

  console.log(
    `\n[char-bg-rm] done. stripped=${stripped} skipped=${skipped} failed=${failed}`,
  );
  if (failed > 0) process.exit(1);
};

main().catch((err) => {
  console.error('[char-bg-rm]', err);
  process.exit(1);
});
