/**
 * Upload comic-strip cast reference images to R2.
 *
 * One-shot script. Pushes the 4 PNGs generated by spike-comic-cast.ts to
 * R2 under reference-images/comic-cast/ so the worker can fetch them by URL
 * at strip-generation time.
 *
 * Usage: pnpm tsx scripts/upload-comic-cast-refs.ts
 * Env required: R2_ENDPOINT, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY,
 *               R2_BUCKET, R2_PUBLIC_URL
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { put } from '@one-colored-pixel/storage';

const CAST_DIR = join(__dirname, 'out', 'spike-comic-cast');
const CAST_IDS = ['colo', 'pip', 'smudge', 'sticky'] as const;

async function run() {
  for (const id of CAST_IDS) {
    const localPath = join(CAST_DIR, `${id}.png`);
    if (!existsSync(localPath)) {
      throw new Error(`Missing local file: ${localPath}`);
    }
    const body = readFileSync(localPath);
    const pathname = `reference-images/comic-cast/${id}.png`;
    console.log(`[upload] Pushing ${id} -> ${pathname}...`);
    const { url } = await put(pathname, body, {
      contentType: 'image/png',
    });
    console.log(`[upload] ${id} -> ${url}`);
  }
  console.log('[upload] All 4 cast refs uploaded.');
}

run().catch((err) => {
  console.error('[upload] Failed:', err);
  process.exit(1);
});
