// Avatar catalog for profile selection.
//
// Was 10 named-colour crayon circles → then 12 species tiles that
// overlapped with the Character Builder picker. Rewritten 2026-05
// as a fresh mix of magical creatures + friendly objects so the
// avatar picker feels distinct from "pick a species for your story"
// and gives the kid more identity options (the dragon kid, the
// rainbow kid, the rocket kid). All face-only chibi heads on
// transparent backgrounds, generated by
// scripts/generate-profile-avatars.ts via gpt-image-2 high then
// bg-stripped via Replicate (851-labs/background-remover).
//
// Each entry carries a soft tinted background — different per
// avatar so 12 round avatars don't all look like the same orange
// ball.

export type Avatar = {
  id: string;
  /** Display label (used as aria-label + the initials fallback). */
  name: string;
  /**
   * R2 key for the illustrated tile. Resolved at render time by
   * `resolveThumbnailUrl` against `NEXT_PUBLIC_R2_PUBLIC_URL`.
   */
  imageKey: string;
  /**
   * Tailwind bg class for the tinted circle behind the illustration.
   * Soft tints so the colour reads without competing with the art.
   * Mirrors the per-item colour variety on the Character Builder
   * species tiles.
   */
  bg: string;
};

export const AVATARS: Avatar[] = [
  // Magical creatures (3) — kid wants to BE the thing.
  // (dragon + unicorn kept despite Character Builder overlap because
  // both are top kid picks; fairy + monster + robot dropped to avoid
  // overlap. mermaid + ghost fill out the magical tier with distinct
  // species from Character Builder.)
  {
    id: 'dragon',
    name: 'Dragon',
    imageKey: 'profile-avatars/dragon.png',
    bg: 'bg-crayon-green/15',
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    imageKey: 'profile-avatars/unicorn.png',
    bg: 'bg-crayon-purple/15',
  },
  {
    id: 'mermaid',
    name: 'Mermaid',
    imageKey: 'profile-avatars/mermaid.png',
    bg: 'bg-crayon-teal/15',
  },
  {
    id: 'ghost',
    name: 'Ghost',
    imageKey: 'profile-avatars/ghost.png',
    bg: 'bg-paper-cream-dark/40',
  },
  // Roleplay / costume identities (3) — face-with-iconic-prop tier.
  {
    id: 'superhero',
    name: 'Superhero',
    imageKey: 'profile-avatars/superhero.png',
    bg: 'bg-crayon-pink/15',
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    imageKey: 'profile-avatars/astronaut.png',
    bg: 'bg-crayon-sky/15',
  },
  {
    id: 'wizard',
    name: 'Wizard',
    imageKey: 'profile-avatars/wizard.png',
    bg: 'bg-crayon-purple/15',
  },
  // Sci-fi (2) — broader-than-real-world identity options.
  {
    id: 'alien',
    name: 'Alien',
    imageKey: 'profile-avatars/alien.png',
    bg: 'bg-crayon-green/15',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    imageKey: 'profile-avatars/rocket.png',
    bg: 'bg-crayon-blue/15',
  },
  // Friendly objects + treats with faces (3) — the abstract /
  // playful tier. Crayon mascot dropped in favour of ice cream
  // (more distinctive kid-identity pick; user preference).
  {
    id: 'ice-cream',
    name: 'Ice Cream',
    imageKey: 'profile-avatars/ice-cream.png',
    bg: 'bg-crayon-pink/15',
  },
  {
    id: 'sun',
    name: 'Sun',
    imageKey: 'profile-avatars/sun.png',
    bg: 'bg-crayon-yellow/20',
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    imageKey: 'profile-avatars/rainbow.png',
    bg: 'bg-crayon-sky/15',
  },
];

// Default avatar for new profiles. `crayon` is the brand-friendly
// no-bias starter (was previously `bunny` from the species set).
export const DEFAULT_AVATAR_ID = 'ice-cream';

// Legacy ID map — every old `crayon-*` ID resolves to a sensible new
// tile so existing profiles in the DB keep rendering after the
// catalog rewrite. No DB migration needed; the resolver
// transparently swaps them. Removing this map is safe once every
// active profile has been re-saved with a new ID (i.e. every parent
// has hit "edit profile" at least once).
const LEGACY_AVATAR_MAP: Record<string, string> = {
  // Original crayon-colour IDs (pre-2026 illustrated avatars).
  'crayon-red': 'dragon',
  'crayon-orange': 'ice-cream',
  'crayon-yellow': 'sun',
  'crayon-green': 'alien',
  'crayon-blue': 'rocket',
  'crayon-purple': 'unicorn',
  'crayon-pink': 'superhero',
  'crayon-brown': 'wizard',
  'crayon-teal': 'mermaid',
  'crayon-coral': 'astronaut',
  // First illustrated set (animals — 2026-05, replaced same month).
  // Map each old species to the most-similar magical / object so
  // existing profiles don't grey-chip after the migration.
  cat: 'ice-cream',
  dog: 'ice-cream',
  bunny: 'fairy',
  fox: 'dragon',
  lion: 'sun',
  panda: 'ghost',
  frog: 'alien',
  turtle: 'mermaid',
  owl: 'wizard',
  // Second illustrated set (magical creatures — 2026-05, swap day).
  // fairy + monster + robot were dropped to avoid overlap with the
  // Character Builder species picker. Map to similar costume picks.
  fairy: 'wizard',
  monster: 'alien',
  robot: 'astronaut',
  // The five never-filled placeholder slots fall through to defaults
  // — anyone with one of these in the DB is a pre-launch test row.
  'avatar-01': 'ice-cream',
  'avatar-02': 'rainbow',
  'avatar-03': 'unicorn',
  'avatar-04': 'dragon',
  'avatar-05': 'astronaut',
  // Schema default — `avatarId String @default("default")` lives on
  // every profile that was created before the picker was wired up
  // (most "Artist" / "Artist (imported)" rows are in this bucket).
  // Without this mapping they render as grey initials chips.
  default: DEFAULT_AVATAR_ID,
};

const resolveLegacy = (avatarId: string): string =>
  LEGACY_AVATAR_MAP[avatarId] ?? avatarId;

// Get avatar by ID. Transparently maps legacy IDs (e.g. `crayon-orange`)
// to their replacement in the new catalog so existing profiles don't
// render as broken.
export const getAvatar = (avatarId: string): Avatar | undefined => {
  const id = resolveLegacy(avatarId);
  return AVATARS.find((avatar) => avatar.id === id);
};

// Every avatar in the new catalog is selectable — no placeholder
// shape any more. Kept as a function so consumers don't import the
// raw array (insulates them from future shape changes).
export const getSelectableAvatars = (): Avatar[] => AVATARS;

// Initials from name as the final visual fallback when the avatar
// image fails to load and we have nothing else to show.
export const getInitials = (name: string): string => {
  return name
    .split(' ')
    .map((word) => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
};
