// Avatar catalog for profile selection.
//
// Was 10 named-colour crayon circles + 5 placeholder slots that
// were never filled. Rewritten as 12 illustrated tiles (9 animals
// + 3 mythical) generated by scripts/generate-profile-avatars.ts
// via gpt-image-2 high — same recipe family as the Character
// Builder species tiles, so the avatar picker reads as the same
// kit as the rest of CC. The illustrations live at R2
// `profile-avatars/<id>.png` and in `public/profile-avatars/` for
// dev. Resolved at render time via the shared `resolveThumbnailUrl`
// helper (env-aware so the same catalog works in dev + prod).
//
// Each entry carries a soft tinted background — same per-tile
// colour variety the Character Builder uses so 12 round avatars
// don't all look like the same orange ball.

export type Avatar = {
  id: string;
  /** Display label (used as aria-label + the initials fallback). */
  name: string;
  /**
   * R2 key for the illustrated tile. Resolved at render time by
   * `resolveThumbnailUrl` against `NEXT_PUBLIC_R2_PUBLIC_URL`.
   */
  imageKey: string;
  /**
   * Tailwind bg class for the tinted circle behind the illustration.
   * Soft tints so the colour reads without competing with the art.
   * Mirrors the per-item colour variety on the Character Builder
   * species tiles.
   */
  bg: string;
};

export const AVATARS: Avatar[] = [
  // Animals (9) — friendly, kid-recognisable, broad species spread
  // so the kid finds one that "feels like them".
  {
    id: 'cat',
    name: 'Cat',
    imageKey: 'profile-avatars/cat.png',
    bg: 'bg-crayon-orange/15',
  },
  {
    id: 'dog',
    name: 'Dog',
    imageKey: 'profile-avatars/dog.png',
    bg: 'bg-crayon-yellow/20',
  },
  {
    id: 'bunny',
    name: 'Bunny',
    imageKey: 'profile-avatars/bunny.png',
    bg: 'bg-crayon-pink/15',
  },
  {
    id: 'fox',
    name: 'Fox',
    imageKey: 'profile-avatars/fox.png',
    bg: 'bg-crayon-orange/20',
  },
  {
    id: 'lion',
    name: 'Lion',
    imageKey: 'profile-avatars/lion.png',
    bg: 'bg-crayon-yellow/15',
  },
  {
    id: 'panda',
    name: 'Panda',
    imageKey: 'profile-avatars/panda.png',
    bg: 'bg-paper-cream-dark/40',
  },
  {
    id: 'frog',
    name: 'Frog',
    imageKey: 'profile-avatars/frog.png',
    bg: 'bg-crayon-green/15',
  },
  {
    id: 'turtle',
    name: 'Turtle',
    imageKey: 'profile-avatars/turtle.png',
    bg: 'bg-crayon-teal/15',
  },
  {
    id: 'owl',
    name: 'Owl',
    imageKey: 'profile-avatars/owl.png',
    bg: 'bg-crayon-purple/15',
  },
  // Mythical (3) — the kid who wants to be a unicorn / dragon /
  // robot. Same three species the Character Builder offers, so the
  // mental vocabulary carries through.
  {
    id: 'unicorn',
    name: 'Unicorn',
    imageKey: 'profile-avatars/unicorn.png',
    bg: 'bg-crayon-purple/15',
  },
  {
    id: 'dragon',
    name: 'Dragon',
    imageKey: 'profile-avatars/dragon.png',
    bg: 'bg-crayon-green/15',
  },
  {
    id: 'robot',
    name: 'Robot',
    imageKey: 'profile-avatars/robot.png',
    bg: 'bg-crayon-teal/15',
  },
];

// Default avatar for new profiles. `bunny` is the welcoming common-
// case pick; was previously `crayon-orange` from the legacy palette.
export const DEFAULT_AVATAR_ID = 'bunny';

// Legacy ID map — every old `crayon-*` ID resolves to a sensible new
// tile so existing profiles in the DB keep rendering after the
// catalog rewrite. No DB migration needed; the resolver
// transparently swaps them. Removing this map is safe once every
// active profile has been re-saved with a new ID (i.e. every parent
// has hit "edit profile" at least once).
const LEGACY_AVATAR_MAP: Record<string, string> = {
  'crayon-red': 'fox',
  'crayon-orange': 'cat',
  'crayon-yellow': 'lion',
  'crayon-green': 'frog',
  'crayon-blue': 'turtle',
  'crayon-purple': 'unicorn',
  'crayon-pink': 'bunny',
  'crayon-brown': 'panda',
  'crayon-teal': 'turtle',
  'crayon-coral': 'fox',
  // The five never-filled placeholder slots fall through to defaults
  // — anyone with one of these in the DB is a pre-launch test row.
  'avatar-01': 'cat',
  'avatar-02': 'dog',
  'avatar-03': 'unicorn',
  'avatar-04': 'dragon',
  'avatar-05': 'robot',
  // Schema default — `avatarId String @default("default")` lives on
  // every profile that was created before the picker was wired up
  // (most "Artist" / "Artist (imported)" rows are in this bucket).
  // Without this mapping they render as grey initials chips.
  default: DEFAULT_AVATAR_ID,
};

const resolveLegacy = (avatarId: string): string =>
  LEGACY_AVATAR_MAP[avatarId] ?? avatarId;

// Get avatar by ID. Transparently maps legacy IDs (e.g. `crayon-orange`)
// to their replacement in the new catalog so existing profiles don't
// render as broken.
export const getAvatar = (avatarId: string): Avatar | undefined => {
  const id = resolveLegacy(avatarId);
  return AVATARS.find((avatar) => avatar.id === id);
};

// Every avatar in the new catalog is selectable — no placeholder
// shape any more. Kept as a function so consumers don't import the
// raw array (insulates them from future shape changes).
export const getSelectableAvatars = (): Avatar[] => AVATARS;

// Initials from name as the final visual fallback when the avatar
// image fails to load and we have nothing else to show.
export const getInitials = (name: string): string => {
  return name
    .split(' ')
    .map((word) => word[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
};
