import type { GridColorMap } from "@/types";

/**
 * AI-assisted 5x5 GridColorMap for the onboarding welcome SVG.
 * Base generated by Gemini Pro analyzing the welcome-coloring-v8.png image,
 * then refined for Colo's brand colors and better visual variety.
 * This map is used by the "Auto Color" feature during onboarding.
 */
export const ONBOARDING_COLOR_MAP: GridColorMap = {
  sceneDescription:
    "A cheerful party scene with Colo the crayon mascot waving, a WELCOME banner, balloons, confetti, and bushes",
  gridColors: [
    // Row 1 (top) — banner flags and sky
    {
      row: 1,
      col: 1,
      element: "banner flag and sky",
      suggestedColor: "#E53935",
      colorName: "Cherry Red",
      reasoning: "A bright red flag for the party!",
    },
    {
      row: 1,
      col: 2,
      element: "banner and sky",
      suggestedColor: "#1E88E5",
      colorName: "Sky Blue",
      reasoning: "A cheerful blue party sky",
    },
    {
      row: 1,
      col: 3,
      element: "WELCOME banner",
      suggestedColor: "#FDD835",
      colorName: "Sunshine Yellow",
      reasoning: "A sunny yellow welcome banner!",
    },
    {
      row: 1,
      col: 4,
      element: "banner flag and sky",
      suggestedColor: "#FB8C00",
      colorName: "Sunset Orange",
      reasoning: "An orange flag adds color",
    },
    {
      row: 1,
      col: 5,
      element: "banner flag and sky",
      suggestedColor: "#8E24AA",
      colorName: "Grape Purple",
      reasoning: "A purple flag to finish the banner",
    },

    // Row 2 — balloons, crayon top, confetti
    {
      row: 2,
      col: 1,
      element: "balloon and confetti",
      suggestedColor: "#EC407A",
      colorName: "Bubblegum Pink",
      reasoning: "A pink balloon floating in the air!",
    },
    {
      row: 2,
      col: 2,
      element: "sky and confetti",
      suggestedColor: "#1E88E5",
      colorName: "Sky Blue",
      reasoning: "Blue sky behind the confetti",
    },
    {
      row: 2,
      col: 3,
      element: "crayon tip",
      suggestedColor: "#E53935",
      colorName: "Cherry Red",
      reasoning: "Colo's crayon tip is bright red!",
    },
    {
      row: 2,
      col: 4,
      element: "balloon and confetti",
      suggestedColor: "#AB47BC",
      colorName: "Lavender",
      reasoning: "A pretty purple balloon floats by",
    },
    {
      row: 2,
      col: 5,
      element: "balloon and sky",
      suggestedColor: "#FB8C00",
      colorName: "Sunset Orange",
      reasoning: "A bright orange balloon for fun!",
    },

    // Row 3 — Colo mascot body area
    {
      row: 3,
      col: 1,
      element: "balloon string and sky",
      suggestedColor: "#1E88E5",
      colorName: "Sky Blue",
      reasoning: "Blue sky around the balloons",
    },
    {
      row: 3,
      col: 2,
      element: "Colo arm and wrapper",
      suggestedColor: "#FF7043",
      colorName: "Coral",
      reasoning: "Colo's warm orange-coral body",
    },
    {
      row: 3,
      col: 3,
      element: "Colo face and belly",
      suggestedColor: "#FFCC80",
      colorName: "Skin Tone",
      reasoning: "Colo's friendly warm belly!",
    },
    {
      row: 3,
      col: 4,
      element: "Colo arm and wrapper",
      suggestedColor: "#FF7043",
      colorName: "Coral",
      reasoning: "Colo's matching body color",
    },
    {
      row: 3,
      col: 5,
      element: "balloon string and sky",
      suggestedColor: "#FDD835",
      colorName: "Sunshine Yellow",
      reasoning: "Yellow sky near the balloon",
    },

    // Row 4 — bushes and lower crayon
    {
      row: 4,
      col: 1,
      element: "bushes and ground",
      suggestedColor: "#43A047",
      colorName: "Grass Green",
      reasoning: "Lush green bushes at the party!",
    },
    {
      row: 4,
      col: 2,
      element: "bushes and ground",
      suggestedColor: "#2E7D32",
      colorName: "Forest",
      reasoning: "Deeper green bushes for contrast",
    },
    {
      row: 4,
      col: 3,
      element: "Colo legs and base",
      suggestedColor: "#1E88E5",
      colorName: "Sky Blue",
      reasoning: "Colo's blue lower wrapper stripe",
    },
    {
      row: 4,
      col: 4,
      element: "bushes and ground",
      suggestedColor: "#43A047",
      colorName: "Grass Green",
      reasoning: "Greenery continues across the party",
    },
    {
      row: 4,
      col: 5,
      element: "bushes and ground",
      suggestedColor: "#2E7D32",
      colorName: "Forest",
      reasoning: "More lovely green bushes here",
    },

    // Row 5 (bottom) — ground and confetti
    {
      row: 5,
      col: 1,
      element: "ground and confetti",
      suggestedColor: "#FFD54F",
      colorName: "Gold",
      reasoning: "Golden party ground with confetti!",
    },
    {
      row: 5,
      col: 2,
      element: "ground and confetti",
      suggestedColor: "#FFD54F",
      colorName: "Gold",
      reasoning: "Party confetti on golden ground",
    },
    {
      row: 5,
      col: 3,
      element: "ground and Colo feet",
      suggestedColor: "#FFD54F",
      colorName: "Gold",
      reasoning: "Colo stands on the golden ground",
    },
    {
      row: 5,
      col: 4,
      element: "ground and confetti",
      suggestedColor: "#FFD54F",
      colorName: "Gold",
      reasoning: "More confetti on the ground!",
    },
    {
      row: 5,
      col: 5,
      element: "ground and confetti",
      suggestedColor: "#FFD54F",
      colorName: "Gold",
      reasoning: "The party ground sparkles gold!",
    },
  ],
};
