/**
 * Content-reel schema — the data shape every content reel renders from.
 *
 * Phase A2: replaces the original `Stat` shape with a `kind`-discriminated
 * `ContentReel` so the same templates + cover pipeline can serve stats,
 * facts, tips, and myth-busts without forking the visual system. See
 * ~/.claude/plans/content-reels.md for the full plan.
 *
 * Local copy lives here for the Phase 0 spike. Will be hoisted to
 * `packages/coloring-core/src/content-reels/catalogue.ts` in Phase B so
 * the Vercel publish route + worker renderer share one source.
 *
 * Field-level notes worth knowing:
 *   - `centerBlock` replaces the previous `bigNumber`. Stat reels still
 *     pass numeric strings ("7+ hrs", "-15%"); other kinds pass short
 *     phrases ("False", "Color before bedtime"). The renderer's reveal
 *     beat branches on `kind` to pick the right visual treatment.
 *   - `coverTeaser` is the question-shaped string the Satori cover JPEG
 *     uses to hook the scroll. Generated by Claude at write-time
 *     (different prompt per `kind`); manual override always wins. If
 *     missing the cover falls back to `hook`, but that's intentionally
 *     less compelling so we want all production rows to have one.
 *   - `factCheckedAt` / `factCheckConfidence` / `factCheckNotes` are the
 *     Perplexity Sonar verification fields. Mandatory for stat/fact/myth
 *     before publish; optional for tip. Re-checked weekly by the
 *     fact-check cron — items >180d old get re-verified.
 */

export type ContentReelKind = "stat" | "fact" | "tip" | "myth";

export type ContentReelCategory =
  | "screen-time"
  | "attention"
  | "anxiety"
  | "fine-motor"
  | "creativity"
  | "family-bonding"
  | "parenting-tip"
  // Added for the broader content surface:
  | "brain-development"
  | "sleep"
  | "common-misconception";

export type ContentReelTemplate = "shock" | "warm" | "quiet";

export type FactCheckConfidence = "high" | "medium" | "low";

/**
 * Per-word caption track. Times are in milliseconds, RELATIVE to the
 * voice clip's start (not the composition's start). The renderer offsets
 * to its beat at draw time.
 *
 * Production: ElevenLabs's `with_timestamps` mode returns these directly.
 * Spike: hand-tuned per item in sample-stats.ts.
 */
export type CaptionToken = {
  text: string;
  fromMs: number;
  toMs: number;
};

export type ContentReel = {
  /** Stable slug — used to dedup against last-30d posts. */
  id: string;

  /** Discriminant — drives reveal-beat treatment + fact-check rules. */
  kind: ContentReelKind;

  /** Setup line said before the centre block lands. Problem-first framing. */
  hook: string;
  /** Per-word timing for the hook voice clip, in clip-relative ms. */
  hookTokens?: CaptionToken[];

  /** Resolution narration — said over the reveal/payoff beat. */
  payoff: string;
  /** Per-word timing for the payoff voice clip, in clip-relative ms. */
  payoffTokens?: CaptionToken[];

  /**
   * The dramatic reveal block. Interpretation depends on `kind`:
   *   stat: "7+ hrs" | "-15%"            (numeric)
   *   fact: "Brain regions involved"     (short phrase)
   *   tip:  "Color before bedtime"       (action phrase)
   *   myth: "False" | "True"             (verdict)
   */
  centerBlock: string;

  /**
   * Question-shaped string the cover JPEG uses to hook the scroll. Points
   * at the obscured (pixelated) centre block. Generated by Claude at
   * write-time; falls back to `hook` if missing.
   */
  coverTeaser?: string;

  /**
   * Source attribution + URL. Required for stat/fact/myth, optional for
   * tip. Validation should reject publishes where these are missing on a
   * non-tip kind.
   */
  sourceTitle?: string;
  sourceUrl?: string;

  /** Drives default template selection. */
  category: ContentReelCategory;
  /** Override category → template default if needed. */
  templateOverride?: ContentReelTemplate;

  /** ISO date (yyyy-mm-dd) of the last Perplexity Sonar verification. */
  factCheckedAt?: string;
  /** Sonar's confidence rating. Below 'high' → don't auto-publish. */
  factCheckConfidence?: FactCheckConfidence;
  /** Sonar's reasoning, stored for editorial audit. */
  factCheckNotes?: string;
};

/** Default category → template mapping. */
export const CATEGORY_TEMPLATE: Record<
  ContentReelCategory,
  ContentReelTemplate
> = {
  // Existing stat categories
  "screen-time": "shock",
  attention: "shock",
  anxiety: "warm",
  "fine-motor": "warm",
  creativity: "warm",
  "family-bonding": "quiet",
  "parenting-tip": "quiet",
  // New categories (mostly fact / tip / myth surface)
  "brain-development": "warm",
  sleep: "quiet",
  "common-misconception": "shock",
};

export const templateForContentReel = (
  reel: ContentReel,
): ContentReelTemplate =>
  reel.templateOverride ?? CATEGORY_TEMPLATE[reel.category];
