import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  Font,
} from '@react-pdf/renderer';
import SvgToReactPdf from '@/components/SvgToReactPdf/SvgToReactPdf';

Font.register({
  family: 'Tondo Bold',
  src: 'https://chunkycrayon.com/fonts/tondo-bold.ttf',
});

Font.register({
  family: 'Rooney Sans',
  src: 'https://chunkycrayon.com/fonts/rooney-sans-regular.ttf',
});

export type BundlePage = {
  /** Coloring image title shown as the page heading. */
  title: string;
  /** Raw SVG string of the coloring page line art. */
  svgContent: string;
};

export type BundlePdfDocumentProps = {
  /** Bundle name shown on the cover. */
  bundleName: string;
  /** Bundle marketing tagline shown below the name. */
  bundleTagline: string;
  /** Square listing hero JPG as a data URL. Reused as the PDF cover so
   * the printable matches the product page. The square aspect leaves
   * cream space top + bottom on A4 portrait — accepted as a known
   * trade-off until the worker grows an A4-shaped cover variant. */
  coverImageDataUrl: string;
  /** Pre-rendered QR-code SVG string that links back to the bundle's
   * product page. Same pattern as ColoringPageDocument — keeps the
   * printable connected to the brand for anyone who finds a sheet. */
  qrCodeSvg: string;
  /** Ordered coloring pages making up the bundle interior. */
  pages: BundlePage[];
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#FFFFFF',
    padding: 36,
    flexDirection: 'column',
  },
  // Square listing JPG centered on A4. Cream background matches the JPG's
  // own backdrop so the letterbox bands read as one continuous surface.
  //
  // TODO: when bundle volume justifies it, refactor
  // apps/chunky-crayon-worker/src/listings/templates/Hero.tsx to accept
  // dimensions (currently hardcoded to LISTING_SIZE = 1200) so the worker
  // can render an A4-portrait cover variant alongside the square one.
  // That gives PDFs an edge-to-edge cover identical to the product page,
  // generated by a single source of truth. Until then, the cream gaps
  // top + bottom on the cover page are a known cosmetic trade-off.
  coverPage: {
    backgroundColor: '#FFFAF5',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  coverImageWrapper: {
    width: '100%',
  },
  coverImage: {
    width: '100%',
    height: 'auto',
    objectFit: 'contain',
  },
  body: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  coloringImage: {
    width: '100%',
    height: 'auto',
  },
  footer: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTop: '1 solid #EEE',
    paddingTop: 10,
  },
  footerText: {
    fontFamily: 'Tondo Bold',
    fontSize: 9,
    color: '#999',
    flex: 1,
    paddingRight: 12,
  },
  footerQrCode: {
    width: 48,
    height: 48,
  },
});

const BundlePdfDocument: React.FC<BundlePdfDocumentProps> = ({
  bundleName,
  bundleTagline,
  coverImageDataUrl,
  qrCodeSvg,
  pages,
}) => {
  return (
    <Document title={bundleName} author="Chunky Crayon">
      {/* Cover — square listing JPG, centered. Same brand asset as the
          product-page hero so the printable feels of-a-piece. */}
      <Page size="A4" orientation="portrait" style={styles.coverPage}>
        <View style={styles.coverImageWrapper}>
          <Image src={coverImageDataUrl} style={styles.coverImage} />
        </View>
      </Page>

      {/* One page per coloring image, in bundleOrder. No header — the
          coloring image gets the full page. Footer kept as a discreet
          brand mark. */}
      {pages.map((p, i) => (
        <Page
          key={`${p.title}-${i}`}
          size="A4"
          orientation="portrait"
          style={styles.page}
        >
          <View style={styles.body}>
            <SvgToReactPdf
              svgString={p.svgContent}
              style={styles.coloringImage}
            />
          </View>

          <View style={styles.footer}>
            <Text style={styles.footerText}>
              {bundleTagline} · Chunky Crayon
            </Text>
            <SvgToReactPdf svgString={qrCodeSvg} style={styles.footerQrCode} />
          </View>
        </Page>
      ))}
    </Document>
  );
};

export default BundlePdfDocument;
